// Compile the GResource bundle (icons + UI definition) into the
// binary. We list every file we want bundled under `resources/`; the
// gresource.xml is generated by this build script so we don't have to
// keep it in sync manually.
//
// Why this is in build.rs: GTK looks up icons, GMenu XML, and CSS by
// resource URL `resource:///com/airvzxf/bose-connect-gui/...`; the
// runtime needs the binary data embedded so it can mmap them on
// startup without an install step.

use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    // Re-run when any resource file changes.
    println!("cargo:rerun-if-changed=resources");
    println!("cargo:rerun-if-env-changed=BOSE_GUI_GRESOURCE");

    let resources_dir = Path::new("resources");
    if !resources_dir.exists() {
        // Allow the crate to build even when the resource tree is
        // empty (e.g. running `cargo check` on a stripped clone).
        println!("cargo:warning=no `resources/` directory; skipping gresource bundle");
        return;
    }

    // Emit a gresource.xml listing every file under `resources/`.
    let manifest = resources_dir.join("gresource.xml");
    let xml = build_gresource_manifest(resources_dir);
    let mut f = fs::File::create(&manifest).expect("create gresource.xml");
    f.write_all(xml.as_bytes()).expect("write gresource.xml");
    println!("cargo:rerun-if-changed={}", manifest.display());

    // glib-compile-resources needs to write the .gresource file to
    // the *output* dir, but the path its argument evaluates to is
    // relative to the current working directory. Cargo invokes the
    // build script with cwd set to OUT_DIR; we explicitly point
    // glib-compile-resources there.
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let target = Path::new(&out_dir)
        .join("gresource.gresource")
        .to_str()
        .unwrap()
        .to_string();

    glib_build_tools::compile_resources(
        &[resources_dir.to_path_buf()],
        manifest.to_str().unwrap(),
        &target,
    );

    // Re-run also when the generated gresource file changes (the
    // OS file watcher doesn't always see the dependency correctly).
    println!("cargo:rerun-if-changed={}", target);
}

fn build_gresource_manifest(resources_dir: &Path) -> String {
    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    out.push_str("<gresources>\n");
    out.push_str("  <gresource prefix=\"/com/airvzxf/bose-connect-gui\">\n");

    fn walk(dir: &Path, base: &Path, out: &mut String) {
        let entries = match fs::read_dir(dir) {
            Ok(e) => e,
            Err(_) => return,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk(&path, base, out);
            } else if path
                .extension()
                .is_some_and(|e| e == "svg" || e == "css" || e == "ui" || e == "png" || e == "xml")
                && path.file_name().is_some_and(|n| n != "gresource.xml")
            {
                let rel = path
                    .strip_prefix(base)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                out.push_str(&format!("    <file>{rel}</file>\n"));
            }
        }
    }

    walk(resources_dir, resources_dir, &mut out);
    out.push_str("  </gresource>\n");
    out.push_str("</gresources>\n");
    out
}
