version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["actions/*", "github/*"]
      third-party:
        patterns: ["*"]
        exclude-patterns: ["actions/*", "github/*"]
    commit-message:
      prefix: "ci"
    labels: ["dependencies", "ci"]
